[project]
name = "mitol-django-google-sheets-deferrals"
version = "2023.5.30"

[tool.bumpver]
current_version = "2023.5.30"
version_pattern = "YYYY.MM.DD[.INC0]"

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]
"__init__.py" = [
    '__version__ = "{version}"',
]