[project]
name = "mitol-django-olposthog"
version = "2024.4.25"

[tool.bumpver]
current_version = "2024.4.25"
version_pattern = "YYYY.MM.DD[.INC0]"

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]
"__init__.py" = [
    '__version__ = "{version}"',
]